mexc:
  ws:
    enabled: true
    endpoint: wss://wbs-api.mexc.com/ws
    pingPeriodSec: 25
    rotateAfterHours: 23
    reconnectBackoffBaseSec: 2
    reconnectBackoffMaxSec: 60
    maxSubscriptionsPerConn: 30
  user:
    enabled: false   # ⬅️ выключили глобальный user-WS

logging:
  level:
    root: INFO
    com.suhoi.mexcwebsocket: DEBUG

app:
  telegram:
    botToken: 8013267846:AAFRYVCj2Et9cRZZmKdxjq7JhnzG8O82mck
    botUsername: drain_mexc_bot
